# Generated by Django 4.2.3 on 2023-11-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_topic_options_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='link',
            field=models.CharField(default='https://github.com/MengyiG', max_length=100),
        ),
    ]
