# Generated by Django 4.2.3 on 2023-11-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_portal_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='name',
            new_name='title',
        ),
    ]
